# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.FileField(default=b'/book_images/no_image.png', upload_to=b'book_images'),
        ),
    ]
