# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20161002_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectibleimage',
            name='image',
            field=models.FileField(upload_to=b'book_images'),
        ),
    ]
