# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20161002_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.FileField(upload_to=b'book_images/'),
        ),
        migrations.AlterField(
            model_name='collectibleimage',
            name='image',
            field=models.FileField(upload_to=b'book_images/'),
        ),
    ]
