# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20161008_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=b'book_images/'),
        ),
    ]
